cleanup

diff --git a/root/etc/s6-overlay/s6-rc.d/init-config-java/run b/root/etc/s6-overlay/s6-rc.d/init-config-java/run
--- a/root/etc/s6-overlay/s6-rc.d/init-config-java/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-config-java/run
@@ -3,14 +3,12 @@
 # install java versions supplied in JAVA_VERSIONS variable
 if [ -n "${JAVA_VERSIONS}" ]; then
     for i in ${JAVA_VERSIONS//,/ }; do
-        if [[ "$i" =~ ^([7-9]|1[0-7])$ ]]; then
-            TO_INSTALL="openjdk${i}-jre $TO_INSTALL"
+        if ! apk add --no-cache -q openjdk${i}-jre; then
+            echo "Could not install openjdk${i}-jre! Is it a supported java version?"
         else
-            echo "Can't find openjdk${i}-jre! Is it a supported java version?"
+            echo "Installed openjdk${i}-jre"
         fi
     done
-    echo "Installing versions of java: $TO_INSTALL"
-    apk add $TO_INSTALL &>/dev/null
 else
-    echo "No java versions are specified in the JAVA_VERSIONS variable."
+    echo "No java versions are specified in the 'JAVA_VERSIONS' variable."
 fi
